#!/usr/bin/env sh

set xou -pipefail 

# Exit and return to menu on host
if [[ -f /run/.containerenv && -r /run/.containerenv ]]; then
  kill -9 $PPID
fi

host="$(cat /etc/hostname) (host)"
envs="$host\n$(distrobox list | tail -n +2 | tr '|' ',' | cut -d , -f 2 | tr -d ' ')"
host_prev=${HOST_PREV:="cat /etc/hostname"}
env_prev=${ENV_PREV:="distrobox list | head -n 1 && distrobox list | grep ' {}'"}
preview="[[ {} == '$host' ]] && ($host_prev) || ($env_prev)"

# Loop if snv is run from the container
ret="1"
while [[ "$ret" != "0" ]]; do
  choice="$(printf "$envs" | fzf --height 10% --reverse --preview "$preview")"

  case $choice in
    "$host")
      break
      ;;
    "")
      break
      ;;
    *)
      distrobox enter $choice 
      ret="$?"
      ;;
  esac
done
